/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserNotInFraccRouteImport } from './routes/user-not-in-fracc'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as TenantIdRouteRouteImport } from './routes/$tenantId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TenantIdIndexRouteImport } from './routes/$tenantId/index'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminFraccionamientosRouteImport } from './routes/admin/fraccionamientos'
import { Route as TenantIdUsuariosRouteImport } from './routes/$tenantId/usuarios'
import { Route as TenantIdPerfilRouteImport } from './routes/$tenantId/perfil'
import { Route as TenantIdDocumentosRouteImport } from './routes/$tenantId/documentos'
import { Route as TenantIdCasaRouteImport } from './routes/$tenantId/casa'
import { Route as TenantIdAnunciosRouteImport } from './routes/$tenantId/anuncios'
import { Route as TenantIdAdminCasasRouteImport } from './routes/$tenantId/adminCasas'
import { Route as TenantIdAdminPagosRouteImport } from './routes/$tenantId/admin-pagos'
import { Route as TenantIdAdminDocumentosRouteImport } from './routes/$tenantId/admin-documentos'
import { Route as TenantIdAdminAnunciosRouteImport } from './routes/$tenantId/admin-anuncios'
import { Route as TenantIdPagosIndexRouteImport } from './routes/$tenantId/pagos/index'
import { Route as ApiUploadDocumentRouteImport } from './routes/api/upload/document'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as TenantIdPagosSuccessRouteImport } from './routes/$tenantId/pagos/success'
import { Route as TenantIdPagosCancelRouteImport } from './routes/$tenantId/pagos/cancel'

const UserNotInFraccRoute = UserNotInFraccRouteImport.update({
  id: '/user-not-in-fracc',
  path: '/user-not-in-fracc',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIdRouteRoute = TenantIdRouteRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TenantIdIndexRoute = TenantIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFraccionamientosRoute = AdminFraccionamientosRouteImport.update({
  id: '/fraccionamientos',
  path: '/fraccionamientos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TenantIdUsuariosRoute = TenantIdUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const TenantIdPerfilRoute = TenantIdPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const TenantIdDocumentosRoute = TenantIdDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const TenantIdCasaRoute = TenantIdCasaRouteImport.update({
  id: '/casa',
  path: '/casa',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const TenantIdAnunciosRoute = TenantIdAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const TenantIdAdminCasasRoute = TenantIdAdminCasasRouteImport.update({
  id: '/adminCasas',
  path: '/adminCasas',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const TenantIdAdminPagosRoute = TenantIdAdminPagosRouteImport.update({
  id: '/admin-pagos',
  path: '/admin-pagos',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const TenantIdAdminDocumentosRoute = TenantIdAdminDocumentosRouteImport.update({
  id: '/admin-documentos',
  path: '/admin-documentos',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const TenantIdAdminAnunciosRoute = TenantIdAdminAnunciosRouteImport.update({
  id: '/admin-anuncios',
  path: '/admin-anuncios',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const TenantIdPagosIndexRoute = TenantIdPagosIndexRouteImport.update({
  id: '/pagos/',
  path: '/pagos/',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const ApiUploadDocumentRoute = ApiUploadDocumentRouteImport.update({
  id: '/api/upload/document',
  path: '/api/upload/document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIdPagosSuccessRoute = TenantIdPagosSuccessRouteImport.update({
  id: '/pagos/success',
  path: '/pagos/success',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const TenantIdPagosCancelRoute = TenantIdPagosCancelRouteImport.update({
  id: '/pagos/cancel',
  path: '/pagos/cancel',
  getParentRoute: () => TenantIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenantId': typeof TenantIdRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/user-not-in-fracc': typeof UserNotInFraccRoute
  '/$tenantId/admin-anuncios': typeof TenantIdAdminAnunciosRoute
  '/$tenantId/admin-documentos': typeof TenantIdAdminDocumentosRoute
  '/$tenantId/admin-pagos': typeof TenantIdAdminPagosRoute
  '/$tenantId/adminCasas': typeof TenantIdAdminCasasRoute
  '/$tenantId/anuncios': typeof TenantIdAnunciosRoute
  '/$tenantId/casa': typeof TenantIdCasaRoute
  '/$tenantId/documentos': typeof TenantIdDocumentosRoute
  '/$tenantId/perfil': typeof TenantIdPerfilRoute
  '/$tenantId/usuarios': typeof TenantIdUsuariosRoute
  '/admin/fraccionamientos': typeof AdminFraccionamientosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/$tenantId/': typeof TenantIdIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$tenantId/pagos/cancel': typeof TenantIdPagosCancelRoute
  '/$tenantId/pagos/success': typeof TenantIdPagosSuccessRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/upload/document': typeof ApiUploadDocumentRoute
  '/$tenantId/pagos/': typeof TenantIdPagosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/user-not-in-fracc': typeof UserNotInFraccRoute
  '/$tenantId/admin-anuncios': typeof TenantIdAdminAnunciosRoute
  '/$tenantId/admin-documentos': typeof TenantIdAdminDocumentosRoute
  '/$tenantId/admin-pagos': typeof TenantIdAdminPagosRoute
  '/$tenantId/adminCasas': typeof TenantIdAdminCasasRoute
  '/$tenantId/anuncios': typeof TenantIdAnunciosRoute
  '/$tenantId/casa': typeof TenantIdCasaRoute
  '/$tenantId/documentos': typeof TenantIdDocumentosRoute
  '/$tenantId/perfil': typeof TenantIdPerfilRoute
  '/$tenantId/usuarios': typeof TenantIdUsuariosRoute
  '/admin/fraccionamientos': typeof AdminFraccionamientosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/$tenantId': typeof TenantIdIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$tenantId/pagos/cancel': typeof TenantIdPagosCancelRoute
  '/$tenantId/pagos/success': typeof TenantIdPagosSuccessRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/upload/document': typeof ApiUploadDocumentRoute
  '/$tenantId/pagos': typeof TenantIdPagosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tenantId': typeof TenantIdRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/user-not-in-fracc': typeof UserNotInFraccRoute
  '/$tenantId/admin-anuncios': typeof TenantIdAdminAnunciosRoute
  '/$tenantId/admin-documentos': typeof TenantIdAdminDocumentosRoute
  '/$tenantId/admin-pagos': typeof TenantIdAdminPagosRoute
  '/$tenantId/adminCasas': typeof TenantIdAdminCasasRoute
  '/$tenantId/anuncios': typeof TenantIdAnunciosRoute
  '/$tenantId/casa': typeof TenantIdCasaRoute
  '/$tenantId/documentos': typeof TenantIdDocumentosRoute
  '/$tenantId/perfil': typeof TenantIdPerfilRoute
  '/$tenantId/usuarios': typeof TenantIdUsuariosRoute
  '/admin/fraccionamientos': typeof AdminFraccionamientosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/$tenantId/': typeof TenantIdIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$tenantId/pagos/cancel': typeof TenantIdPagosCancelRoute
  '/$tenantId/pagos/success': typeof TenantIdPagosSuccessRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/upload/document': typeof ApiUploadDocumentRoute
  '/$tenantId/pagos/': typeof TenantIdPagosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tenantId'
    | '/admin'
    | '/accept-invite'
    | '/login'
    | '/not-found'
    | '/user-not-in-fracc'
    | '/$tenantId/admin-anuncios'
    | '/$tenantId/admin-documentos'
    | '/$tenantId/admin-pagos'
    | '/$tenantId/adminCasas'
    | '/$tenantId/anuncios'
    | '/$tenantId/casa'
    | '/$tenantId/documentos'
    | '/$tenantId/perfil'
    | '/$tenantId/usuarios'
    | '/admin/fraccionamientos'
    | '/admin/usuarios'
    | '/$tenantId/'
    | '/admin/'
    | '/$tenantId/pagos/cancel'
    | '/$tenantId/pagos/success'
    | '/api/stripe/webhook'
    | '/api/upload/document'
    | '/$tenantId/pagos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/not-found'
    | '/user-not-in-fracc'
    | '/$tenantId/admin-anuncios'
    | '/$tenantId/admin-documentos'
    | '/$tenantId/admin-pagos'
    | '/$tenantId/adminCasas'
    | '/$tenantId/anuncios'
    | '/$tenantId/casa'
    | '/$tenantId/documentos'
    | '/$tenantId/perfil'
    | '/$tenantId/usuarios'
    | '/admin/fraccionamientos'
    | '/admin/usuarios'
    | '/$tenantId'
    | '/admin'
    | '/$tenantId/pagos/cancel'
    | '/$tenantId/pagos/success'
    | '/api/stripe/webhook'
    | '/api/upload/document'
    | '/$tenantId/pagos'
  id:
    | '__root__'
    | '/'
    | '/$tenantId'
    | '/admin'
    | '/accept-invite'
    | '/login'
    | '/not-found'
    | '/user-not-in-fracc'
    | '/$tenantId/admin-anuncios'
    | '/$tenantId/admin-documentos'
    | '/$tenantId/admin-pagos'
    | '/$tenantId/adminCasas'
    | '/$tenantId/anuncios'
    | '/$tenantId/casa'
    | '/$tenantId/documentos'
    | '/$tenantId/perfil'
    | '/$tenantId/usuarios'
    | '/admin/fraccionamientos'
    | '/admin/usuarios'
    | '/$tenantId/'
    | '/admin/'
    | '/$tenantId/pagos/cancel'
    | '/$tenantId/pagos/success'
    | '/api/stripe/webhook'
    | '/api/upload/document'
    | '/$tenantId/pagos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantIdRouteRoute: typeof TenantIdRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  UserNotInFraccRoute: typeof UserNotInFraccRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiUploadDocumentRoute: typeof ApiUploadDocumentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-not-in-fracc': {
      id: '/user-not-in-fracc'
      path: '/user-not-in-fracc'
      fullPath: '/user-not-in-fracc'
      preLoaderRoute: typeof UserNotInFraccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantId': {
      id: '/$tenantId'
      path: '/$tenantId'
      fullPath: '/$tenantId'
      preLoaderRoute: typeof TenantIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$tenantId/': {
      id: '/$tenantId/'
      path: '/'
      fullPath: '/$tenantId/'
      preLoaderRoute: typeof TenantIdIndexRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/fraccionamientos': {
      id: '/admin/fraccionamientos'
      path: '/fraccionamientos'
      fullPath: '/admin/fraccionamientos'
      preLoaderRoute: typeof AdminFraccionamientosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$tenantId/usuarios': {
      id: '/$tenantId/usuarios'
      path: '/usuarios'
      fullPath: '/$tenantId/usuarios'
      preLoaderRoute: typeof TenantIdUsuariosRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/$tenantId/perfil': {
      id: '/$tenantId/perfil'
      path: '/perfil'
      fullPath: '/$tenantId/perfil'
      preLoaderRoute: typeof TenantIdPerfilRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/$tenantId/documentos': {
      id: '/$tenantId/documentos'
      path: '/documentos'
      fullPath: '/$tenantId/documentos'
      preLoaderRoute: typeof TenantIdDocumentosRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/$tenantId/casa': {
      id: '/$tenantId/casa'
      path: '/casa'
      fullPath: '/$tenantId/casa'
      preLoaderRoute: typeof TenantIdCasaRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/$tenantId/anuncios': {
      id: '/$tenantId/anuncios'
      path: '/anuncios'
      fullPath: '/$tenantId/anuncios'
      preLoaderRoute: typeof TenantIdAnunciosRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/$tenantId/adminCasas': {
      id: '/$tenantId/adminCasas'
      path: '/adminCasas'
      fullPath: '/$tenantId/adminCasas'
      preLoaderRoute: typeof TenantIdAdminCasasRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/$tenantId/admin-pagos': {
      id: '/$tenantId/admin-pagos'
      path: '/admin-pagos'
      fullPath: '/$tenantId/admin-pagos'
      preLoaderRoute: typeof TenantIdAdminPagosRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/$tenantId/admin-documentos': {
      id: '/$tenantId/admin-documentos'
      path: '/admin-documentos'
      fullPath: '/$tenantId/admin-documentos'
      preLoaderRoute: typeof TenantIdAdminDocumentosRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/$tenantId/admin-anuncios': {
      id: '/$tenantId/admin-anuncios'
      path: '/admin-anuncios'
      fullPath: '/$tenantId/admin-anuncios'
      preLoaderRoute: typeof TenantIdAdminAnunciosRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/$tenantId/pagos/': {
      id: '/$tenantId/pagos/'
      path: '/pagos'
      fullPath: '/$tenantId/pagos/'
      preLoaderRoute: typeof TenantIdPagosIndexRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/api/upload/document': {
      id: '/api/upload/document'
      path: '/api/upload/document'
      fullPath: '/api/upload/document'
      preLoaderRoute: typeof ApiUploadDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantId/pagos/success': {
      id: '/$tenantId/pagos/success'
      path: '/pagos/success'
      fullPath: '/$tenantId/pagos/success'
      preLoaderRoute: typeof TenantIdPagosSuccessRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/$tenantId/pagos/cancel': {
      id: '/$tenantId/pagos/cancel'
      path: '/pagos/cancel'
      fullPath: '/$tenantId/pagos/cancel'
      preLoaderRoute: typeof TenantIdPagosCancelRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
  }
}

interface TenantIdRouteRouteChildren {
  TenantIdAdminAnunciosRoute: typeof TenantIdAdminAnunciosRoute
  TenantIdAdminDocumentosRoute: typeof TenantIdAdminDocumentosRoute
  TenantIdAdminPagosRoute: typeof TenantIdAdminPagosRoute
  TenantIdAdminCasasRoute: typeof TenantIdAdminCasasRoute
  TenantIdAnunciosRoute: typeof TenantIdAnunciosRoute
  TenantIdCasaRoute: typeof TenantIdCasaRoute
  TenantIdDocumentosRoute: typeof TenantIdDocumentosRoute
  TenantIdPerfilRoute: typeof TenantIdPerfilRoute
  TenantIdUsuariosRoute: typeof TenantIdUsuariosRoute
  TenantIdIndexRoute: typeof TenantIdIndexRoute
  TenantIdPagosCancelRoute: typeof TenantIdPagosCancelRoute
  TenantIdPagosSuccessRoute: typeof TenantIdPagosSuccessRoute
  TenantIdPagosIndexRoute: typeof TenantIdPagosIndexRoute
}

const TenantIdRouteRouteChildren: TenantIdRouteRouteChildren = {
  TenantIdAdminAnunciosRoute: TenantIdAdminAnunciosRoute,
  TenantIdAdminDocumentosRoute: TenantIdAdminDocumentosRoute,
  TenantIdAdminPagosRoute: TenantIdAdminPagosRoute,
  TenantIdAdminCasasRoute: TenantIdAdminCasasRoute,
  TenantIdAnunciosRoute: TenantIdAnunciosRoute,
  TenantIdCasaRoute: TenantIdCasaRoute,
  TenantIdDocumentosRoute: TenantIdDocumentosRoute,
  TenantIdPerfilRoute: TenantIdPerfilRoute,
  TenantIdUsuariosRoute: TenantIdUsuariosRoute,
  TenantIdIndexRoute: TenantIdIndexRoute,
  TenantIdPagosCancelRoute: TenantIdPagosCancelRoute,
  TenantIdPagosSuccessRoute: TenantIdPagosSuccessRoute,
  TenantIdPagosIndexRoute: TenantIdPagosIndexRoute,
}

const TenantIdRouteRouteWithChildren = TenantIdRouteRoute._addFileChildren(
  TenantIdRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminFraccionamientosRoute: typeof AdminFraccionamientosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminFraccionamientosRoute: AdminFraccionamientosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantIdRouteRoute: TenantIdRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  UserNotInFraccRoute: UserNotInFraccRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiUploadDocumentRoute: ApiUploadDocumentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
